### PR TITLE
Modernize and update the library to es6

### PR DESCRIPTION
**Pull request by alexjoverm**
This PR basically modernizes the library with the following features:
 - Code updated to es6: much more readable code taking all advantages of the latest version of the language :)
 - Uses webpack over browserify
 - Adds yarn lock

### CODE REVIEW

**Comment by alexjoverm** [comment]
Hello @RobertWHurst, just pinging in case you haven't received the notification of this PR. It's been opened for 3 weeks :)

**Comment by RobertWHurst** [comment]
This is great, Thanks for the work. Sorry for the late response. I like this change, but there needs to be a build process for the NPM package as Node does not yet implement the new module system. It's also currently unclear how node will implement this change. I know it seems strange to worry about such things for a front end project, but I want this code to remain polymorphic.

**Comment by alexjoverm** [comment]
Hi Robert!

Lucky you! There is a build process, that's where webpack with babel comes in the commit 654d122. Plus, if you look closely at the webpack config, you'll see it is setup as a UMD library, so it will work in all AMD, commonjs, ES module and directly in the browser :).

As I tested it was working, did you encounter any problems?

**Comment by RobertWHurst** [comment]
I'm familiar with your build process. I did look. What I mean is that the package.json's main points at index.js which in your PR uses ES6 modules. That won't work with node.

**Comment by alexjoverm** [comment]
Oh, I see what you mean. It would be a matter of changing it to dist/keyboard.js. I'll change it and test it. Do you have any particular node example?

**Comment by alexjoverm** [comment]
@RobertWHurst done

**Comment by alexjoverm** [comment]
@RobertWHurst I see this still pending, is there any problem?

**Comment by RobertWHurst** [comment]
@alexjoverm I'm closing this PR. I appreciate the effort you went to on this PR, but I'd like to hold off on this change for now. Thanks for your contribution none the less.

**Pull request closed without merging**
