### PR TITLE
Feature: window implemented as a readable stream

### PR DESCRIPTION
**Pull request by formula1**
Not sure if this will be accepted but I figured I might as well contribute to an existing repository than remake the wheel.

Grabbing a keyboard events is not only dedicated to the browser (though holding may be the easiest)

As it stands you may use [runtimes keyboard](https://github.com/runtimejs/runtime/blob/5335759cfdf89e224fe875b5e40777ab9abe6206/js/driver/ps2/keyboard.js), [keypress to listen for stdin events](https://github.com/TooTallNate/keypress), the browser and if you look for the correct file, you can `cat dev/input/eventX` as I'm doing right now.

Theres a valid argument to be made that all key pressing should follow the browsers golden standard (because the browser has always done everything right). But I made these changes in hope I can convince you of a direction I chosen to take: Higher dependence on streams. 

The advantage streams have are

1. Can make a Keyboard Writable that you can pipe other streams into `windowReader.pipe(keyboard)` or `process.stdin.pipe(keyPressTransform).pipe(keyboard)`
2. Allow developers to have their code visually represent what is happening. `new Keyboard(something)` is a black box. You don't know what's happening underneath or what dirty things keyboard is doing to it.  Piping on the other hand makes it very apparent what is happening. Theres some events that need to get read and piped to the Keyboard processer
3. 'pausing' (cork I believe for writables) and all other stream goodies don't have to be reimplemented
4. future developers that want to provide their IO to your library have a standardized way of hooking into your library instead of attempting to use some sort of window/element shim.
5. There are a TON of streams libraries while eventListener libraries usually turn into stream libraries
6. You are feeding the actual event to the dispatched listeners. A non-w3c event may not be ok. As a result, each developer will have to implement the w3c event. This slightly defeats the purpose of having a library for both node and browser

On the otherside

- Adds bloat
- Can create alternative constructor for process and etc
- I can't think of much else but can you plame me? I wrote this pull request

### CODE REVIEW

**Comment by RobertWHurst** [comment]
Hey @formula1, thanks for sharing your PR. It's an interesting idea, however as you mention there is a lot more code post your changes. 4,000 additional lines is a lot to swallow. I'm also not sure about adding a stream API to this version of KeyboardJS. That said I can see streams being the basis for a new keyboard binding library as the benefits you pointed out, most notably, compatibility with other stream based libraries would be useful. I won't merge this as it's simply to large, but I do appreciate the work you put into this. I'll encourage you to share your branch though :)

**Comment by formula1** [comment]
Is there a reason why?

**Comment by formula1** [comment]
Ah, I didn't notice 4,000 bytes added to the dist. That is certianly a big amount of bloat. I'll continue on with my own branch. a shame I can't use this library but I guess thats fine

**Comment by RobertWHurst** [comment]
@formula1 I'm glad you like the library. If you can achieve the readable API without so much additional code I'm happy to review again. Cheers!

**Pull request closed without merging**
