### PR TITLE
master

### PR DESCRIPTION
**Pull request by cotejp**
I added the ability to pass preventRepeat and preventDefault params to the KeyboardJS.on() function (through an optional 4th param).

### CODE REVIEW

**Comment by RobertWHurst** [comment]
Dam you put a lot of work into this! Good going :)
I'm going to set aside some time to review and we'll go from there.

**Comment by cotejp** [comment]
Now that I look back at it, I'm not sure you should pull in all the changes that I did. I think what's relevant for you is the preventRepeat and preventDefault behaviour. After that, the changes are really geared toward my own usage which is with keyboard emulators.

**Comment by RobertWHurst** [comment]
I agree. You've forked. Not going to clone what you've done. But I might borrow some of your innovations.

That said, I've been working on KeyboardJS 2 so they might be bumped to that release in the coming months.

Had a look at your fork. Mind if I ask what inspired your fork? What did you create it for? I saw you added a few arcade machine key layouts.

Nice work :)

**Comment by cotejp** [comment]
I'm working on developing a set of tools that can be used to create physical computing projects with JavaScript (I will be launching a site dedicated to that somewhere this spring). In this particular case, I needed a way to easily work with keyboard emulators. I actually wrote an article about precisely that in my forthcoming site. You can view it here if you are curious: 

http://tangiblejs.com/posts/switches-keyboard-emulators-javascript

Cheers!

**Pull request closed without merging**
