### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by vegetableman**
fixed missing semi, missing var, unused variables, storing array length to speed up for loops.

### CODE REVIEW

**Comment by RobertWHurst** [comment]
Storing array lengths is unnecessary. Modern VMs have inline variable caching.

**Comment by vegetableman** [comment]
Thanks for sharing the info @RobertWHurst

**Comment by RobertWHurst** [comment]
You may find this talk on V8 interesting => https://youtu.be/Z_q6iw3h48s?t=303

**Comment by vegetableman** [comment]
On my watch list. Thanks again. :+1:

**Pull request closed without merging**
