### PR TITLE
Fixed empty binding issue

### LINKED ISSUE #118: Issue when using empty combo with multiple bindings
If a binding is created with no chars ('') and then another binding is added a crash occurs.

### PR DESCRIPTION
**Pull request by dropmann**
Closes #118

### CODE REVIEW

**Comment by jonathon-love** [comment]
hey @RobertWHurst,

we're keen for this fix too! anything we can do to expediate things?

with thanks

**Comment by McPo** [comment]
There appears to be issues with this PR when using contexts.

image

**Comment by McPo** [comment]
unbind is also broken.

Inorder to correct the issue I had to change lines 105-106 in keyboard.js

from 
```
    var comboMatches          = !keyComboStr && !listener.keyCombo ||
                                listener.keyCombo.isEqual(keyComboStr);
```
to
```
var comboMatches          = !listener.keyCombo || listener.keyCombo.isEqual(keyComboStr);
```

Otherwise it attempts to call isEqual on a null value.

Otherwise works fine.

**Comment by jonathon-love** [comment]
thanks @McPo!

unfortunately i need to get the fix into npm.

**Comment by dropmann** [comment]
thanks @McPo for pointing this out, it is a problem. Although, there is one thing worth changing with your fix. It removes the comparison of the empty keyComboStr to a possible null listener.keyCombo as true and includes a result of true when listener.keyCombo is null and the keyComboStr being compared to is not empty, which should be false. 

so rather than

```javascript
var comboMatches = !listener.keyCombo || listener.keyCombo.isEqual(keyComboStr);
```

i think it would be better to do

```javascript
var comboMatches = !keyComboStr && !listener.keyCombo || 
                   listener.keyCombo && listener.keyCombo.isEqual(keyComboStr);
```

I've made the changes on my side already. Thanks for pointing it out.

**Comment by RobertWHurst** [comment]
👍

**Comment by RobertWHurst** [comment]
Published as v2.3.2

**Comment by RobertWHurst** [comment]
Sorry for the late review here. Been extremely busy with work related projects and I haven't had the metal bandwidth. Hope this helps :)

**Pull request merged**
